In [2]:
import numpy as np
arr=np.array([3,4,2,5,1,0])
print(np.sort(arr))

[0 1 2 3 4 5]


In [3]:
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [5]:
import numpy as np
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [10]:
import numpy as np
arr=np.array([[3,2,4,5,0],[3,5,3,8,9]])
print(np.sort(arr))

[[0 2 3 4 5]
 [3 3 5 8 9]]
