In [2]:
import numpy as np
arr=np.array([41,42,43,44])
x=np.where(arr==42)
print(x)

(array([1], dtype=int64),)


In [3]:
import numpy as np
arr=np.array([41,42,43,44])
x=np.where(arr%2==0)
print(x)

(array([1, 3], dtype=int64),)


In [4]:
import numpy as np
arr=np.array([41,42,43,44])
x=np.where(arr%2==1)
print(x)

(array([0, 2], dtype=int64),)


In [6]:
import numpy as np
arr=np.array([41,42,43,44])
x=np.searchsorted(arr,42)
print(x)

1


In [7]:
import numpy as np
arr=np.array([41,42,43,44])
x=np.searchsorted(arr,42,side="right")
print(x)

2


In [8]:
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]
