In [2]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr=np.concatenate((arr1,arr2))
print(newarr)

[1 2 3 4 5 6 7 8]


In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
newarr=np.concatenate((arr1,arr2),axis=1)
print(newarr)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr=np.stack((arr1,arr2),axis=1)
print(newarr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [8]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr=np.vstack((arr1,arr2))
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr=np.dstack((arr1,arr2))
print(newarr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [10]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
newarr=np.hstack((arr1,arr2))
print(newarr)

[1 2 3 4 5 6 7 8]
