In [1]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
newarr=np.array_split(arr,2)
print(newarr)

[array([10, 20, 30]), array([40, 50, 60])]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [2]:
import numpy as np
arr=np.array([12, 4, 8, 16, 2])
sorted_arr=np.sort(arr)[::-1]
print(sorted_arr)

[16 12  8  4  2]


In [4]:
import numpy as np
arr=np.array([[3,2,1],[9,8,7]])
print(np.sort(arr))

[[1 2 3]
 [7 8 9]]


In [7]:
import numpy as np
arr=np.array([2,4,6,8,10])
x=np.where(arr==8)
print(x)

(array([3], dtype=int64),)


In [9]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
x=np.where(arr>50)
print(x)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [10]:
import numpy as np
arr=np.array([10,15,20,25,30])
filter_arr=[]
for element in arr:
    if element > 20:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, False, True, True]
[25 30]


In [22]:
import numpy as np
arr=np.array([[15,20,25],[30,35,40],[45,50,55]])
filter_arr=arr[(arr % 5!=0) | (arr % 10 !=0)]
print(filter_arr)


[15 25 35 45 55]
