In [9]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6]])
print(arr.shape)

(3, 2)


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.shape)

(5,)


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(3,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [18]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [20]:
import numpy as np
arr1=np.array([1,2])
arr2=np.array([3,4])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4]


In [25]:
import numpy as np
arr1=np.array([1,2])
arr2=np.array([3,4])
arr=np.stack((arr1,arr2) , axis=1)
print(arr)

[[1 3]
 [2 4]]
