In [4]:
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5])
newarr=random.permutation(arr)
print("Original array : " , arr)
print("New array : " , newarr)

Original array :  [1 2 3 4 5]
New array :  [2 1 3 4 5]


In [6]:
from numpy import random
import numpy as np
arr=np.array([[1,2],[3,4],[5,6]])
random.shuffle(arr)
print(arr)

[[1 2]
 [5 6]
 [3 4]]


In [7]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(10,10))
print(x)

[[7 7 5 3 7 5 7 7 5 7]
 [7 7 5 7 7 7 7 7 5 5]
 [7 7 7 7 7 3 7 5 5 7]
 [3 7 5 7 5 7 7 7 7 3]
 [7 7 5 7 7 7 5 7 7 7]
 [3 5 7 7 5 7 7 5 3 3]
 [5 7 7 7 5 7 7 7 5 3]
 [7 5 5 7 7 5 7 7 3 5]
 [7 7 7 7 7 5 7 7 5 5]
 [5 3 7 5 5 7 7 7 7 7]]


In [8]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,3,5))
print(x)

[[[5 7 5 7 7]
  [7 5 5 5 7]
  [5 3 5 3 7]]

 [[7 3 5 7 5]
  [7 7 7 7 5]
  [5 7 7 7 7]]

 [[7 5 7 7 5]
  [7 7 7 7 7]
  [5 7 7 7 7]]]
