In [2]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([0,0,0,0,0,1,1,0,2])
print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2
[1 1 2]


In [5]:
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
print(csr_matrix(arr).data)

[1 1 2]


In [6]:
import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
print(csr_matrix(arr).count_nonzero())

3


In [8]:
mat = csr_matrix(arr)
mat.eliminate_zeros()
print(mat.data)

[1 1 2]


In [15]:
mat=csr_matrix(arr)
mat.sum_duplicates()
print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [16]:
mat=csr_matrix(arr)
mat.sum_duplicates()
print(mat.data)

[1 1 2]


In [17]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
newarr=csr_matrix(arr).tocsc()
print(newarr)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2


In [18]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
newarr=csr_matrix(arr).tocsc()
print(newarr.data)

[1 1 2]


In [20]:
import numpy as np
from scipy.sparse import csc_matrix
arr=np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
newarr=csc_matrix(arr).tocsr()
print(newarr)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [21]:
import numpy as np
from scipy.sparse import csc_matrix
arr=np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
newarr=csc_matrix(arr).tocsr()
print(newarr.data)

[1 1 2]
