In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [2]:
import numpy as np
arr=np.array(["apple" ,"banana" , "cherry"])
print(arr.dtype)

<U6


In [3]:
import numpy as np
arr=np.array([1,2,3,4] , dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
import numpy as np
arr=np.array([1,2,3,4] , dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [5]:
import numpy as np
arr=np.array([1.2,2.2,3.1])
new_arr=arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


In [6]:
import numpy as np
arr=np.array([1.2,2.2,3.1])
new_arr=arr.astype('int')
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


In [7]:
import numpy as np
arr=np.array([1,0,2])
new_Arr=arr.astype(bool)
print(new_Arr)
print(new_Arr.dtype)

[ True False  True]
bool


In [8]:
import numpy as np
arr=np.array([-1,0,1])
new_arr=arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[ True False  True]
bool
