<a href="https://colab.research.google.com/github/Prash7621/Data-Science/blob/main/D9numpydatatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr=np.array(["apple" ,"banana" , "cherry"])
print(arr.dtype)

<U6


In [ ]:
import numpy as np
arr=np.array([1,2,3,4] , dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4] , dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
import numpy as np
arr=np.array([1.2,2.2,3.1])
new_arr=arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


In [ ]:
import numpy as np
arr=np.array([1.2,2.2,3.1])
new_arr=arr.astype('int')
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int64


In [ ]:
import numpy as np
arr=np.array([1,0,2])
new_Arr=arr.astype(bool)
print(new_Arr)
print(new_Arr.dtype)

[ True False  True]
bool


In [ ]:
import numpy as np
arr=np.array([-1,0,1])
new_arr=arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[ True False  True]
bool
